# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-deploy-helmfile
  description: 'Deploy on Kubernetes with Helmfile'
  homepage: https://cloudposse.com/accelerate
  topics: github-action

